# Generated by Django 5.0.1 on 2024-01-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='idade',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
